99 completer getdatasetid
InseeFr/Magma pull request #102
Opened 2023-10-18 14:17 UTC by HugoBouttes

#99

2023-10-20 15:29 UTC, FBibonne requested changes

2023-10-23 09:03 UTC, GuyleneTandeauDeMarsac commented on src/main/java/fr/insee/rmes/modelSwagger/dataset/DataSetModelSwagger.java
>  public class DataSetModelSwagger implements Serializable  {
4. fait-on pareil pour les constructeurs ? (@AllArgsConstructor)

2023-10-23 11:38 UTC, GuyleneTandeauDeMarsac commented on src/main/java/fr/insee/rmes/modelSwagger/dataset/DataSetModelSwagger.java
> +    private String disseminationStatus;
A voir avec le métier
Peut-être pour ValidationState dont les valeurs possibles sont "Publiée" et "Provisoire, jamais publiée"

2023-10-23 12:27 UTC, GuyleneTandeauDeMarsac commented on src/main/java/fr/insee/rmes/modelSwagger/dataset/DataSetModelSwagger.java
> +    public DataSetModelSwagger(String id, List<Title> title, String uri, String modified, String created, String validationState, String contributor, String creator, String disseminationStatus) {
Que veux-tu dire ?

2023-10-23 12:28 UTC, GuyleneTandeauDeMarsac commented on src/main/java/fr/insee/rmes/modelSwagger/dataset/DataSetModelSwagger.java
> +    public DataSetModelSwagger(String id, List<Title> title, String uri, String modified, String created, String validationState, List<ThemeModelSwagger> themeModelSwaggerS) {
Que veux-tu dire ?

2023-10-23 12:30 UTC, GuyleneTandeauDeMarsac commented on src/main/java/fr/insee/rmes/modelSwagger/dataset/Label.java
> +public class Label {
fait

2023-10-23 12:31 UTC, GuyleneTandeauDeMarsac commented on src/main/java/fr/insee/rmes/modelSwagger/dataset/LandingPage.java
> +public class LandingPage {
fait

2023-10-23 12:32 UTC, GuyleneTandeauDeMarsac commented on src/main/java/fr/insee/rmes/modelSwagger/dataset/Temporal.java
> +    public Temporal() {
fait

2023-10-23 12:33 UTC, GuyleneTandeauDeMarsac commented on src/main/java/fr/insee/rmes/modelSwagger/dataset/Structure.java
> +    public Structure() {
fait

2023-10-23 12:33 UTC, GuyleneTandeauDeMarsac commented on src/main/java/fr/insee/rmes/modelSwagger/dataset/LandingPage.java
> +    public LandingPage() {
fait

2023-10-23 12:33 UTC, GuyleneTandeauDeMarsac commented on src/main/java/fr/insee/rmes/modelSwagger/dataset/Label.java
> +    public Label() {
fait

2023-10-23 12:44 UTC, GuyleneTandeauDeMarsac commented on src/main/java/fr/insee/rmes/services/datasets/DataSetsImpl.java
>      protected DataSetModelSwagger findDataSetModelSwagger(String id) throws RmesException, JsonProcessingException {
On a factorisé. Est-ce qu'il faudrait encore plus factoriser, selon le graphe ?

2023-10-23 12:58 UTC, GuyleneTandeauDeMarsac commented on src/main/java/fr/insee/rmes/services/datasets/DataSetsImpl.java
>      public String getDataSetByIDFilterByDateMaj (String id) throws RmesException, JsonProcessingException {
il est prévu de revoir avec le métier comment on renomme dateMiseAJour (rien à voir avec la variable dateMiseAJour) : 2 services différents selon la valeur (true ou false), à différencier donc

2023-10-23 14:05 UTC, GuyleneTandeauDeMarsac commented on src/main/java/fr/insee/rmes/services/datasets/DataSetsImpl.java
>                  ObjectMapper jsonResponse2 = new ObjectMapper();
fait

2023-11-06 10:15 UTC, GuyleneTandeauDeMarsac commented on src/main/java/fr/insee/rmes/modelSwagger/dataset/DataSetModelSwagger.java
> +    public DataSetModelSwagger(String id, List<Title> title, String uri, String modified, String created, String validationState, String contributor, String creator, String disseminationStatus) {
vu avec Fabrice : objectif = éviter des erreurs d'inversion. Limite d'un constructeur = 5 éléments
créer un type Creator avec un String dedans => on aura public DataSetModelSwagger(...,Creator creator, ....)

2023-11-06 10:42 UTC, GuyleneTandeauDeMarsac commented on src/main/java/fr/insee/rmes/services/datasets/DataSetsImpl.java
>      public String getDataSetByIDFilterByDateMaj (String id) throws RmesException, JsonProcessingException {
vu avec Fabrice : renommer la méthode getDataSetByIDFilterByDateMaj en getDataSetByIDSummary par ex

2023-11-06 10:47 UTC, GuyleneTandeauDeMarsac commented on src/main/java/fr/insee/rmes/modelSwagger/dataset/DataSetModelSwagger.java
> +    private String disseminationStatus;
vu avec Fabrice : voir la solution technique pour faire une enum (lien entre objet Java et Jackson), la solution essayée était la bonne, voir comment finaliser la mise en oeuvre

2023-11-06 13:11 UTC, GuyleneTandeauDeMarsac commented on src/main/java/fr/insee/rmes/services/datasets/DataSetsImpl.java
>      public String getDataSetByIDFilterByDateMaj (String id) throws RmesException, JsonProcessingException {
fait

2023-11-06 15:00 UTC, GuyleneTandeauDeMarsac commented on src/main/java/fr/insee/rmes/modelSwagger/dataset/DataSetModelSwagger.java
> +    public DataSetModelSwagger(String id, List<Title> title, String uri, String modified, String created, String validationState, String contributor, String creator, String disseminationStatus) {
fait

2023-11-07 13:58 UTC, merged