feat : add issued, temporal, modified and numSeries to patch/dataset/…
InseeFr/Magma pull request #170
Opened 2024-04-19 07:16 UTC by HugoBouttes

…{id}
#167

2024-04-26 12:22 UTC, GuyleneTandeauDeMarsac commented on src/main/java/fr/insee/rmes/services/datasets/DataSetsImpl.java
>          try {
Gérer le cas où aucun des champs possibles n'est renseigné : retourner un code HTTP 400
Actuellement, renvoie un 200 avec dans le message (entre autres) :
  "status": 404,
  "error": "Not Found",

2024-05-06 10:00 UTC, FBibonne requested changes
Vérifier les points supplméntaires suivants :
- la méthode DataSetsServices.findDistributions ne semble plus être utilisée
- DataSetsImpl :
  - le constructeur déclaré avec l'argument freemarkerUtils devrait faire un appel au constructeur super
  - l.55 dateMiseAJour == "" => remplacer par une méthode isEmpty()
  
  Je ne vois pas de test pour la méthode patchDataset : est-il oublié ? Ca permettrait de vérifier que les différents cas de retour depuis Bauhaus sont bien testés (le restClient pourra faciliter les tests)

2024-05-06 10:00 UTC, FBibonne commented on src/main/java/fr/insee/rmes/services/datasets/DataSetsServices.java
> +import org.json.JSONObject;
Import inutile

2024-05-06 10:00 UTC, FBibonne commented on src/main/java/fr/insee/rmes/services/datasets/DataSetsImpl.java
>              throw new RuntimeException(e);
Il semble que seuls IOException et InterruptedException sont utiles : à encapsuler dans une RmeException

2024-05-06 10:00 UTC, FBibonne commented on src/main/java/fr/insee/rmes/services/datasets/DataSetsImpl.java
> +    public String patchDataset(String datasetId, String stringPatchDataset, String token) throws RmesException, MalformedURLException {
Ne renvoyer que RmesException

2024-05-06 10:00 UTC, FBibonne commented on src/main/java/fr/insee/rmes/services/datasets/DataSetsImpl.java
>              HttpClient client = HttpClient.newHttpClient();
à placer dans un try with resource ou sinon utiliser RestClient de spring

2024-05-06 10:00 UTC, FBibonne commented on src/main/java/fr/insee/rmes/services/datasets/DataSetsImpl.java
>              HttpRequest request = HttpRequest.newBuilder()
Utiliser des constantes pour les clés et les valeurs des header sur le contenu (cf. classe HttpHeaders de Spring)

2024-05-06 10:00 UTC, FBibonne commented on src/main/java/fr/insee/rmes/services/datasets/DataSetsImpl.java
>              logger.trace("user "+id + " ("+ email + ") has just patched the dataset :" + datasetId);
le niveau de la log doit vraiment être à trace ?

2024-05-06 10:00 UTC, FBibonne commented on src/main/java/fr/insee/rmes/services/datasets/DataSetsImpl.java
>              HttpRequest request = HttpRequest.newBuilder()
Créer un URI de base à déclarer champ final de l'instance pour http://bauhaus/datasets puis dans cette méthode résoudre l'uri finale pour le datasetid en utilisant la méthode resolve

2024-05-06 10:00 UTC, FBibonne commented on src/main/java/fr/insee/rmes/services/datasets/DataSetsImpl.java
>              String urlString = Config.BAUHAUS_URL + "/datasets/" + datasetId + "/observationNumber";
utiliser confg.getBauhausUrl() pour la propriété

2024-05-06 10:00 UTC, FBibonne commented on src/main/java/fr/insee/rmes/services/datasets/DataSetsImpl.java
> +    public JSONObject formattedJsonDataset(JSONObject givenJson) {
Utiliser un objet DTO PathcDataset dans les arguments de la méthode  de controller puis supprimer cette méthode

2024-05-06 10:00 UTC, FBibonne commented on src/main/java/fr/insee/rmes/services/datasets/DataSetsImpl.java
>              String id = getIdFromJWT(token);
encapsuler dans une méthode à part après la requête http pour effectuer la journalisation

2024-05-06 10:00 UTC, FBibonne commented on src/main/java/fr/insee/rmes/services/datasets/DataSetsImpl.java
>              return response.body();
On ne retourne pas le code retour de bauhaus ?

2024-05-06 10:00 UTC, FBibonne commented on src/main/java/fr/insee/rmes/services/datasets/DataSetsImpl.java
>             jwt.replaceAll("Bearer ","");
Appel inutile si on n'utilise pas le retour de la méthode

2024-05-06 10:00 UTC, FBibonne commented on src/main/java/fr/insee/rmes/services/datasets/DataSetsImpl.java
>             jwt.replaceAll("Bearer ","");
idem dans getEtmailFromJWT

2024-05-06 10:00 UTC, FBibonne commented on src/main/java/fr/insee/rmes/services/datasets/DataSetsImpl.java
>      private String getIdFromJWT(String jwt){
Retourner un objet user avec l'id et le mail pour ne pas décoder le tocken plusieurs fois (coûteux en cycle CPU)

2024-05-06 10:00 UTC, FBibonne commented on src/main/java/fr/insee/rmes/services/datasets/DataSetsImpl.java
>      private String getIdFromJWT(String jwt){
Utiliser une classe spécialisée pour la gestion du token

2024-05-06 10:00 UTC, FBibonne commented on src/main/java/fr/insee/rmes/controller/DataSetResources.java
>      private HttpServletRequest request;
Supprimer cet attribut

2024-05-06 10:00 UTC, FBibonne commented on src/main/java/fr/insee/rmes/controller/DataSetResources.java
>          String token = request.getHeader("Authorization");
Utiliser @RequestHeader dans un paramètre de la méthode pour récupérer le tokien

2024-05-06 10:00 UTC, FBibonne commented on src/main/java/fr/insee/rmes/controller/DataSetResources.java
> +            @RequestBody(required = true) String stringPatchDataset
Utiliser un objet DTO pour le body : par exemple PatchDataset avec tous les champs listés dans PatchDatasetProperties

2024-05-06 10:00 UTC, FBibonne commented on src/main/java/fr/insee/rmes/model/datasets/PatchDatasetProperties.java
> +public enum PatchDatasetProperties {
Supprimer cet enum et créer un vrai pojo à la place

2024-05-14 08:33 UTC, HugoBouttes commented on src/main/java/fr/insee/rmes/controller/DataSetResources.java
> +        return this.dataSetsServices.patchDataset(datasetId,stringPatchDataset,token);
no comment

2024-06-18 16:07 UTC, FBibonne approved these changes

2024-06-19 08:04 UTC, JeromeMBourgeois approved these changes

2024-06-21 12:42 UTC, EmmanuelDemey commented
Faudrait déployer cette PR sur dev1. @FBibonne ou @GtanSndil  💪

2024-06-21 12:46 UTC, EmmanuelDemey requested changes

2024-06-21 12:46 UTC, EmmanuelDemey commented on src/main/resources/rmeswsgi.properties
> -spring.security.oauth2.resourceserver.jwt.jwk-set-uri=SECRET
On a l'impression que cette propriété sera à supprimer dans le contrat Puppet @GtanSndil

2024-06-28 08:57 UTC, merged